### ISSUE TITLE
Error running the package build locally 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pridepy#12]
@selvaebi I have built the package locally in my machine and try to run `pridepy -h` here the error: 

```
(pridepy) proteomicsdevmbpr1:pridepy yperez$ pridepy -h 
Traceback (most recent call last):
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/bin/pridepy", line 33, in <module>
    sys.exit(load_entry_point('pridepy==0.0.2', 'console_scripts', 'pridepy')())
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/bin/pridepy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/lib/python3.8/site-packages/pridepy-0.0.2-py3.8.egg/pridepy.py", line 10, in <module>
ModuleNotFoundError: No module named 'peptide'
```

**Comment by ypriverol** [comment]
Running the first example in the web, i got the following error: 

```
pridepy search-projects-by-keywords-and-filters --keyword accession:PXD012353
Traceback (most recent call last):
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/bin/pridepy", line 33, in <module>
    sys.exit(load_entry_point('pridepy==0.0.2', 'console_scripts', 'pridepy')())
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/yperez/local-apps/miniconda3/envs/pridepy/lib/python3.8/site-packages/pridepy-0.0.2-py3.8.egg/pridepy.py", line 136, in search_projects_by_keywords_and_filters
AttributeError: 'Project' object has no attribute 'projects_by_keywords_and_filters'
```
